apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  labels:
    app: bookmyshow-app
    tier: frontend
spec:
  selector:
    app: bookmyshow-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
